<?php

namespace CcMtBundle\Repository;
use CcMtBundle\Entity\Praticien;

/**
 * PraticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PraticienRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPraVisiteurDQL($matricule){
        $query = $this->getEntityManager()->createQuery('Select p from CcMtBundle:Praticien p where p.praVisiteur =:matricule');
        return $query->setParameter('matricule', $matricule)->getResult();
    }
}
