<?php

namespace CcMtBundle\Repository;

/**
 * RapportVisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportVisiteRepository extends \Doctrine\ORM\EntityRepository
{
}
